### PR TITLE
fix: address monaco editor incorrect background in high contrast white on Windows in the component explorer

### LINKED ISSUE #3980: bug: component explorer code samples hard to read in high contrast mode
In high contrast mode (Windows, Edge) the code samples do not have a high enough contrast ratio.

image

**What are the steps to reproduce the issue?**
- Go to https://explore.fast.design/components/fast-accordion
- turn on high contrast light mode
- note code sample in the lower panel

**What behavior did you expect?**
Readable in high-contrast mode with appropriate contrast ratios.

### PR DESCRIPTION
**Pull request by janechu**
# Description

This change replaces the deprecated `<Pivot />` react component with the `@microsoft/fast-components` `<fast-tabs>`.

Screenshot 2021-01-21 174347

## Motivation & context

This not only updates to use the new web components but resolves the contrast issue on high contrast white.

I can only speculate what it was about `<Pivot />` that caused this issue, but since all other variables remained the same during testing and we needed to update these components anyway, that's where the investigation ended.

Resolves #3980

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]

**Review by scomea — APPROVED** [review]

File: sites/fast-component-explorer/app/web-components/index.tsx [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+    guidanceTabPanelContent: React.ComponentClass<{}, any>;
+    definitionTabPanelContent: string;
+    schemaTabPanelContent: string;
+}
+
+export function renderDevToolsTabs(config: RenderDevToolsTabsConfig): React.ReactNode {
+    const styleOverrides: string = `
+        a {
+            color: var(--accent-foreground-rest);
+        }
```
Comment (chrisdholt) [inline sites/fast-component-explorer/app/web-components/index.tsx:33]: Does this already have hover/focus behaviors applied? If not - does it need them?

**Review by chrisdholt — APPROVED** [review]

File: sites/fast-component-explorer/app/web-components/index.tsx (hunk 1 above)
Comment (janechu) [reply sites/fast-component-explorer/app/web-components/index.tsx:33]: We don't have a hover on it currently, could add it in future when we take another design pass.
