### PR TITLE
do not prevent default on tree item click handler

### LINKED ISSUE #5159: fix: can not navigate to URLs from anchor tags in TreeItems
# 🐛 Bug Report

I expect that anchor tags (`<a>` or `<fast-anchor>`) within the <fast-tree-item> element would allow navigation to the specified 'href' setting upon click. This does not happen. 

## 💻 Repro or Code Sample

```
<fast-tree-view>
    <fast-tree-item>Tree item 1<fast-tree-item slot="item"><fast-anchor href="www.google.com">Google</fast-anchor></fast-tree-item>
    </fast-tree-item>
    <fast-tree-item>Tree item 2</fast-tree-item>
</fast-tree-view>
```

## 🤔 Expected Behavior

In the above example, I expect if a user clicks on the 'TreeItem` with the "Google" text that it will navigate the browser to www.google.com. This doesn't happen.

## 😯 Current Behavior

Nothing happens when the TreeItem is clicked.

## 💁 Possible Solution

At a guess, I would suspect that the TreeItem is eating the click event.

## 🔦 Context

We have an app that uses a tree to navigate between various pages. Without this, I have to resort to a programmatic solution, which isn't ideal.

## 🌍 Your Environment

Windows Desktop/Chrome.

### PR DESCRIPTION
**Pull request by chrisdholt**
# Pull Request

## 📖 Description
This issue updates the click handler for tree item to *not* prevent default in order to enable valid scenarios such as anchors within the control.

### 🎫 Issues
closes #5159

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by robarbms — APPROVED** [review]

**Review by nicholasrice — APPROVED** [review]

File: packages/web-components/fast-foundation/src/tree-item/tree-item.ts [hunk 1]
```diff
@@ -102,9 +102,11 @@ export class TreeItem extends FoundationElement {
         }
     };
 
-    public handleClick = (e: MouseEvent): void => {
+    public handleClick = (e: MouseEvent): void | boolean => {
         if (!e.defaultPrevented) {
             this.handleSelected(e);
+            // do not prevent default as it completely eats the click
+            return true;
```
Comment (nicholasrice) [inline packages/web-components/fast-foundation/src/tree-item/tree-item.ts:109]: does it eat the click or do we just not act appropriately because of the `if(!e.defaultPrevented)` check? why are we checking for defaultPrevented here?

Comment (chrisdholt) [reply packages/web-components/fast-foundation/src/tree-item/tree-item.ts:109]: Removing the check here doesn't fix (I am honestly not sure why we are checking here...) - we're definitely eating the click and preventing default as part of our event handling.

**Review by awentzel — APPROVED** [review]
Though I did notice duplicate change instruction files for some reason.

**Comment by chrisdholt** [comment]
> Though I did notice duplicate change instruction files for some reason.

One of these is for foundation and one is for components.
