### PR TITLE
fix type compilations and dupes for style exports, update picker styles to expected convention

### LINKED ISSUE #5346: fix: component style exports cause type complications in fast-components
# 🐛 Bug Report

For `fast-components`, we're exporting the final style constants by creating a new exported const when we haven't changed anything in the original alias. I haven't come across any components which modify their aliased `styles` import, so I don't know if the reassignment is necessary in most cases.

## 💻 Repro or Code Sample

```ts
import { componentStyles as styles } from "./component.styles"; // <- aliased import

export const fastComponent = Component.compose({
    baseName: "component",
    template,
    styles, // <- object property shortcut
    // ...
})

// this doc block should move to ./component.styles.ts
/**
 * Styles for component
 * @public
 */
export const componentStyles = styles; // <- creates duplicated type definition
```

## 😯 Current Behavior

Duplicated type definitions are presented in both `index.ts` as well as in the `*.style.ts` file when built. Also, since the tsdoc block is only present in `index`, meaning the entire style file effectively has no documentation.

## Suggested Fix

We should change the style export to use `as`  instead of creating a new const, and the tsdoc comment should be moved to the `*.styles.ts` file:

```ts
import { componentStyles as styles } from "./component.styles";

export const fastComponent = Component.compose({
    baseName: "component",
    template,
    styles,
    // ...
})

export { styles as componentStyles };

// alternatively, we could do this:
// export { componentStyles } from "./component.styles";
```

```ts
/**
 * Styles for {@link fastComponent}
 * @public
 */
export const componentStyles = // ...
```

### PR DESCRIPTION
**Pull request by chrisdholt**
# Pull Request

### 🎫 Issues
Fixes #5346

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

File: packages/web-components/fast-components/src/picker/index.ts [hunk 1]
```diff
@@ -118,8 +94,4 @@ export const fastPickerListItem = PickerListItem.compose({
     styles: pickerListItemStyles,
 });
 
-/**
- * Styles for PickerListItem
- * @public
- */
-export const PickerListItemStyles = pickerListItemStyles;
+export { pickerStyles, pickerListItemStyles, pickerMenuOptionStyles, pickerMenuStyles };
```
Comment (chrisdholt) [inline packages/web-components/fast-components/src/picker/index.ts:97]: *Technically* this is a break. These are functions and should be exported as such. Picker itself is in alpha, but these were marked public. I'm happy to add deprecated versions of those removed here.

**Review by EisenbergEffect — APPROVED** [review]

File: packages/web-components/fast-components/src/picker/index.ts (hunk 1 above)
Comment (EisenbergEffect) [reply packages/web-components/fast-components/src/picker/index.ts:97]: Probably not an issue. I don't think picker is documented anywhere, so likely folks don't really know this exists.

**Review by robarbms — APPROVED** [review]

File: packages/web-components/fast-components/src/picker/index.ts (hunk 1 above)
Comment (chrisdholt) [reply packages/web-components/fast-components/src/picker/index.ts:97]: My thought as well 👍

**Review by radium-v — APPROVED** [review]
