### PR TITLE
fix: tabs right and left keyboarding in rtl

### LINKED ISSUE #3804: Keyboard navigation in rtl on tabs is broken
**Describe the bug; what happened?**
Keyboard navigation in rtl on tabs is broken, arrow keys are flipped

**What are the steps to reproduce the issue?**

Example:

1. Go to https://stage.explore.fast.design/components/fast-tabs
2. Switch to rtl
3. Focus on tabs
4. use keyboard arrows

### PR DESCRIPTION
**Pull request by SethDonohue**
# Description

Adds direction functionality on Tabs to swap left and right keyboarding when in RTL

## Motivation & context

Fixes #3804 for the Tabs issue

Test:
1) run `yarn dev` in *fast-foundation*
2) run `yarn start` in *sites/fast-component-explorer*
3) View Tabs component and switch between LTR and RTL to test keyboarding

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

File: packages/web-components/fast-foundation/src/tabs/tabs.ts [hunk 1]
```diff
@@ -126,6 +128,11 @@ export class Tabs extends FASTElement {
         }
     }
 
+    private getDirection = (): Direction => {
+        const dirNode: HTMLElement | null = this.parentElement!.closest("[dir]");
```
Comment (nicholasrice) [inline packages/web-components/fast-foundation/src/tabs/tabs.ts:132]: It looks like slider has similar logic to determine direction. Can you move this to a utility that both can leverage so that we can ensure we're determining direction consistently across components?

Comment (SethDonohue) [reply packages/web-components/fast-foundation/src/tabs/tabs.ts:132]: Good call

Comment (SethDonohue) [reply packages/web-components/fast-foundation/src/tabs/tabs.ts:132]: Moved getDirection to a utility.

@marjonlynch Also removed the `setThumbPositionForOrientation` inside of the original function from *Slider* as that is already run in connectedCallback for slider after the `getDirection` function runs.

**Review by EisenbergEffect — APPROVED** [review]

**Review by scomea — APPROVED** [review]
