### PR TITLE
fix: add checks for minimum and maximum out of bounds and add tests for the number type

### LINKED ISSUE #3565: Add testing for the permutator number generation
# Abstract

In the `@microsoft/fast-tooling-wasm` package the permutator project within includes the scaffolding for unit testing.

## Requirements

Update the logic for the following:
- `get_random_number()` might fail if a negative number is assigned. It might be a logic problem if minimum is greater than maximum.
- Consider return ‘\0’ in `get_type_as_string()` since it’s more explicitly returning null.

Add unit tests to check the following:
- Enum numbers are iterated over if provided
- Examples are iterated over if provided (and enums are not)
- Default is used if enum is not provided
- Random numbers are generated with any of the following contraints:
    - minimum
    - maximum
    - exclusiveMinimum
    - exclusiveMaximum
    - multipleOf

### PR DESCRIPTION
**Pull request by janechu**
# Description

Adds checks for minimum and maximum to set the random numbers generated with a range of 100. Adds a check if the minimum is greater than maximum (which should fail validation checks regardless) a number is returned. Adds unit testing for the number type.

## Motivation & context

Resolves #3565

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

File: packages/tooling/fast-tooling-wasm/permutator/__tests__/test.c [hunk 1]
```diff
@@ -2,27 +2,92 @@
...
+        func_to_run, (int) rc.t.number);
+
+    return 1;
+error:
+    return 0;
+}
+
+bool testMinimum(double data)
+{
+
```
Comment (awentzel) [inline packages/tooling/fast-tooling-wasm/permutator/__tests__/test.c:57]: extra line

File: packages/tooling/fast-tooling-wasm/permutator/__tests__/test.c [hunk 2]
```diff
@@ -31,11 +96,221 @@ char *test_dlopen()
     return NULL;
 }
 
+char *test_number_type()
```
Comment (awentzel) [inline packages/tooling/fast-tooling-wasm/permutator/__tests__/test.c:99]: I think it would be nice to see more comprehensive code comments given this is C and doesn't read as well in code as some other languages may.

File: packages/tooling/fast-tooling-wasm/permutator/permutate_number.c [hunk 3]
```diff
@@ -14,21 +16,41 @@ double get_random_number(cJSON *configSchema)
...
+    const bool maximumDefined = (maximum && maximum->valuedouble) || (exclusiveMaximum && exclusiveMaximum->valuedouble);
+
+    const double multipleOfValue = multipleOf && multipleOf->valuedouble
+        ? multipleOf->valuedouble
         : 1;
-    const int minimumValue = minimum->valueint
-        ? minimum->valueint
-        : exclusiveMinimum->valueint
-        ? exclusiveMinimum->valueint + 1
+    double minimumValue = minimum && minimum->valuedouble
```
Comment (awentzel) [inline packages/tooling/fast-tooling-wasm/permutator/permutate_number.c:26]: In some cases you are camelCasing and in others, you are not?  Which pattern should be followed and can we make consistent? for example, "minimumValue" and "valuedouble"
