### PR TITLE
Users/mollykreis/fix menu indent

### LINKED ISSUE #5603: fix: incorrect indention in fast-menu
# 🐛 Bug Report

When adding elements that are not `fast-menu-item` into a `fast-menu`, the indentation of the menu items is incorrectly adjusted when the additional elements have a role of `menuitem`.

## 💻 Repro or Code Sample

With the HTML shown below, setting `role="menuitem"` on the anchor element adjusts the indent of the `fast-menu-items` to 1. Without `role="menuitem"` on the anchor element, the indent of the `fast-menu-items` is 0.

```html
<fast-menu>
    <fast-menu-item>Menu item 1</fast-menu-item>
    <fast-menu-item>Menu item 2</fast-menu-item>
    <fast-menu-item>Menu item 3</fast-menu-item>
    <a href="https://www.fast.design/docs/components" role="menuitem">Menu item 4</a>
</fast-menu>
```

## 🤔 Expected Behavior

Adding elements with a role of 'menuitem' should not affect the indention of other items.

## 😯 Current Behavior
Correct indention without anchor element:
image

Incorrect indention with anchor element:
image

## 💁 Possible Solution
The logic to determine the indention should look only at the 'role' of the element, not its type. See [fast foundation menu](https://github.com/microsoft/fast/blob/af1f8736ae9ff54a7449324bad952865981d1ece/packages/web-components/fast-foundation/src/menu/menu.ts#L224).

## 🔦 Context

I need to create a menu that has hyperlink items and non-hyperlink items. All items should have an indention level of 0.

## 🌍 Your Environment

Windows 10, Chrome 98.0.4758.102

### PR DESCRIPTION
**Pull request by mollykreis**
# Pull Request

## 📖 Description
When an element that is not a MenuItem has a role of 'menuitem' and is added to a Menu, the indentation of other MenuItems is incorrect. This change modifies the logic to determine the appropriate indention of menu items to check only the 'role' of the element, not the element's type.

### 🎫 Issues
Fixes #5603

## 📑 Test Plan
Added one unit test for the case described above.

### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific
- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]

File: packages/web-components/fast-foundation/src/menu/menu.ts [hunk 1]
```diff
@@ -222,21 +222,22 @@ export class Menu extends FoundationElement {
...
-            if (!(el instanceof MenuItem)) {
-                return 1;
+            const role = el.getAttribute("role");
+            if (!role) {
+                return 0;
             }
             if (
-                el.role !== MenuItemRole.menuitem &&
+                role !== MenuItemRole.menuitem &&
                 el.querySelector("[slot=start]") === null
```
Comment (scomea) [inline packages/web-components/fast-foundation/src/menu/menu.ts:231]: We should call querySelector once and put in a const.

**Comment by scomea** [comment]
The part of this that seems unclear to me is what we want the behavior to be.  I agree that adding a non-fast element into the menu triggering an indent of 1 is a bug.  With this change the behavior will be that the presence of non-fast menu items will affect the indent of fast menu items as if they were themselves fast menu items, but these elements are not themselves similarly indented because we only set the indent prop on the fast ones.  Maybe we should be checking these items for a "startColumnCount" property and set that if present so custom items could match the behavior?  Or maybe we just return 0 where we used to return 1 and say that non fast menu items have no impact on indentation at all?  @bheston

**Review by scomea — CHANGES_REQUESTED** [review]

File: packages/web-components/fast-foundation/src/menu/menu.ts [hunk 2]
```diff
@@ -222,21 +222,22 @@ export class Menu extends FoundationElement {
         }
 
         function elementIndent(el: HTMLElement): MenuItemColumnCount {
-            if (!(el instanceof MenuItem)) {
-                return 1;
+            const role = el.getAttribute("role");
+            if (!role) {
```
Comment (chrisdholt) [inline packages/web-components/fast-foundation/src/menu/menu.ts:226]: I'm not sure we want to be supporting things which do not have a role. If the role is set to menuitem, it should behave and slot as such.

Comment (chrisdholt) [reply packages/web-components/fast-foundation/src/menu/menu.ts:226]: I guess we support divider here and that goes full width. I think the guiding principle I'd want to see here is that things are aligned *as menu items* only so long as they have the role of `menuitem`. Hopefully that clears my comment up enough :)

**Comment by scomea** [comment]
> My .02 here is that if someone is adding it _as a menu item_ it needs to visually present as a menu item. If it has a role of `menuitem` it should be treated as a `menuitem`, not just in the tabindex, but also visually.

The method by which we apply indentation to menu items is very specific to fast menu items, we set a property on the instance based on the type:  `if (item instanceof MenuItem) {item.startColumnCount = indent;}`  .  So custom menu items that aren't fast menu items can't easily participate.  I don't think we resolve this in this PR, but if we want custom menu items to be able to participate in the indentation scheme we should open an issue to rethink how it is applied.   I made [an issue](https://github.com/microsoft/fast/issues/5608).

**Comment by chrisdholt** [comment]
> > My .02 here is that if someone is adding it _as a menu item_ it needs to visually present as a menu item. If it has a role of `menuitem` it should be treated as a `menuitem`, not just in the tabindex, but also visually.
> 
> The method by which we apply indentation to menu items is very specific to fast menu items, we set a property on the instance based on the type: `if (item instanceof MenuItem) {item.startColumnCount = indent;}` . So custom menu items that aren't fast menu items can't easily participate. I don't think we resolve this in this PR, but if we want custom menu items to be able to participate in the indentation scheme we should open an issue to rethink how it is applied. I made [an issue](https://github.com/microsoft/fast/issues/5608).

Yeah, the check here should be the same for participation in keyboard behavior, etc - `[role="menuitem"]` as an example. I also noted on the issue that this likely should only live in Components as I don't think *every* menu has or needs to support this behavior. Other systems may have their own approaches to managing this and having this in Foundation seems quite opinionated, especially given we can't override this method. I'd suggest we move that behavior to `fast-components` eventually.

**Comment by scomea** [comment]
> Yeah, the check here should be the same for participation in keyboard behavior, etc - `[role="menuitem"]` as an example. I also noted on the issue that this likely should only live in Components as I don't think _every_ menu has or needs to support this behavior. Other systems may have their own approaches to managing this and having this in Foundation seems quite opinionated, especially given we can't override this method. I'd suggest we move that behavior to `fast-components` eventually.

My other concern, and I think it links to your "opinionated" comment, is that we can't really know the intent of a dev who puts in a custom [role="menuitemcheckbox"].  With this change it will provoke an indent of 1 on the other elements, but if the point of choosing the custom item was to have a very different visual should it affect the indent at all?   Seems ambiguous.  I have a soft preference for a short term fix where non-fast menu items never change the indent of fast menu items, but can live with either approach.

File: packages/web-components/fast-foundation/src/menu/menu.ts (hunk 2 above)
Comment (mollykreis) [reply packages/web-components/fast-foundation/src/menu/menu.ts]: I removed the check since all the elements processed here are guaranteed to have a role of 'menuitem', 'menuitemcheckbox', or 'menuitemradio'.

**Review by scomea — APPROVED** [review]

**Comment by mollykreis** [comment]
@scomea @chrisdholt - Is there anything blocking this PR being merged? Do you need me to do anything else?

**Comment by chrisdholt** [comment]
> @scomea @chrisdholt - Is there anything blocking this PR being merged? Do you need me to do anything else?

I’m going to do a local run; baring any issues there, should be good. We worked through some older spar’s yesterday and hopefully knock a few more out today. Thanks for your patience!

**Comment by chrisdholt** [comment]
Tagging @bheston here as well as this question is around what is expected/correct in this scenario.

I'm noticing that the "start" icon is located _after_ the checkbox and radio. I think this is currently the behavior, but curious if that is ideal/expected. Not blocking this PR for that, but we should check and see if that should be different. Seems odd to me to have start not be at the start.

**Review by chrisdholt — APPROVED** [review]

**Comment by chrisdholt** [comment]
Thank you @mollykreis! This will publish by tomorrow.

**Comment by bheston** [comment]
> Tagging @bheston here as well as this question is around what is expected/correct in this scenario.
> 
> I'm noticing that the "start" icon is located _after_ the checkbox and radio. I think this is currently the behavior, but curious if that is ideal/expected. Not blocking this PR for that, but we should check and see if that should be different. Seems odd to me to have start not be at the start.

Yes, that's expected. The reason is it's less common for menu items to be checkbox or radio, so within a set of other menu items it keeps the icon closely-aligned with the text label and avoids whitespace for all menu items that aren't check or radio.
