### PR TITLE
fix: make resize observer target configurable in html render navigation component

### LINKED ISSUE #5063: Fix uncached image de-sync of the navigation outline
# Description

The outline created by the active item in the canvas area of the Creator should account for image loading (pre-cache).

## Requirements

- Check for images loading in so that the active navigation outline is in the correct coordinates
- Ensure that this is happening before the image has been cached by the browser

### PR DESCRIPTION
**Pull request by williamw2**
# Pull Request

## 📖 Description

Defaulting to the body resulted in scenarios that did not necessarily trigger the resize observer. This PR adds a "resizeobserverselector" attribute to the HTMLRenderNavigation component so that the resize observer target can be specified by the implementing code to ensure that the observer is attached to an element that will resize as content changes.
The new attribute is optional and the component will default to "document.body" if it is not supplied or if the selector specified does not match anything in the document.
This attribute is then used in Creator to specify the containing element which resizes to fit its children and should always trigger the observer whenever the content changes.

### 🎫 Issues
fixes #5063 

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by janechu — APPROVED** [review]

File: packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.ts [hunk 1]
```diff
@@ -59,7 +69,11 @@ export class HTMLRenderLayerNavigation extends HTMLRenderLayer {
             this.handleWindowChange
         );
 
-        this.resizeDetector.observe(document.body);
+        this.resizeDetector.observe(
+            (this.resizeobserverselector
+                ? document.querySelector(this.resizeobserverselector)
```
Comment (EisenbergEffect) [inline packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.ts:74]: Just to be safe, rather than referencing `document` here, you may want to call `this.getRootNode()`. That will get you the document if the component is in the light dom but if it happens to be used inside of another shadow dom, it will get you the shadowRoot. You should be able to perform the querySelector on either (though you might have to cast in TypeScript).

**Review by EisenbergEffect — APPROVED** [review]
Looks good. I made a small recommendation to make the component usable in more contexts.

File: packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.ts (hunk 1 above)
Comment (williamw2) [reply packages/tooling/fast-tooling/src/web-components/html-render-layer-navigation/html-render-layer-navigation.ts]: Done.
