### PR TITLE
fix: increase sophistication of behavior binding and unbinding

### LINKED ISSUE #4242: Using a behavior that dynamically loads styles and uses other behaviors seems to not properly append behaviors
**Describe the bug; what happened?**
We created a behavior that dynamically loads in stylesheets based on a property. We are using this to dynamically load stylesheets based on the `appearance` property for `fast-anchor` and `fast-button`.  The behavior loads in the various styles but not the `behaviors` for the various appearances. Meaning the colors are not loading for the various anchor and button states.

### PR DESCRIPTION
**Pull request by nicholasrice**
# Description
This change implements more sophisticated behavior tracking to make the `Controller` aware of multiple add and remove operations of the same behavior instance. It configures the `Controller` to only bind a behavior instance the first time it is added, and to only unbind a behavior instance after it is removed the number of times it was added. This addresses issues w/ inadvertently unbinding a behavior that was added by multiple sources.

This change also addresses an issue where a `Behavior` which depends on (and adds) *another* `Behavior` would not see it's dependent behavior bound when the initial `Behavior` is bound during the `Controller`'s `onConnectedCallback`.

fixes #4242 

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

File: packages/web-components/fast-element/src/controller.ts [hunk 1]
```diff
@@ -258,10 +272,13 @@ export class Controller extends PropertyChangeNotifier {
         }
 
         const behaviors = this.behaviors;
-
         if (behaviors !== null) {
-            for (let i = 0, ii = behaviors.length; i < ii; ++i) {
-                behaviors[i].bind(element, defaultExecutionContext);
+            const keys = behaviors.keys();
```
Comment (EisenbergEffect) [inline packages/web-components/fast-element/src/controller.ts:276]: How does this approach compare to a normal for/of loop? Is this faster?

**Review by EisenbergEffect — APPROVED** [review]

File: packages/web-components/fast-element/src/controller.ts (hunk 1 above)
Comment (nicholasrice) [reply packages/web-components/fast-element/src/controller.ts]: I didn't actually know you could for/of a Map but of course you can. It appears to be slightly slower in general: https://jsbench.me/pbkkit8zui/1 - I Changed this to use for/of because it's more concise and faster. Thanks for calling this out!

**Review by chrisdholt — APPROVED** [review]
