### PR TITLE
fix: proxy element causes empty check on slots to fail

### LINKED ISSUE #3741: bug: input proxy causes empy label to display
**Describe the bug; what happened?**

When a proxy input is needed it is created in the slot. This prevents the `label__hidden` class from being added.

Edge:
```
<fast-text-field>
  #shadow-root
    <label class="label label__hidden" part="label" for="control">
      <slot></slot>
    </label>
    ...
</fast-text-field>
```

Firefox:
```
<fast-text-field>
  #shadow-root
    <label class="label" part="label" for="control">
      <slot><input /></slot>
    </label>
    ...
</fast-text-field>
```

**What behavior did you expect?**

Label should be hidden in all browsers.

**In what environment did you see the issue?**

* Browser Mozilla FireFox
* Version 1.8.0

### PR DESCRIPTION
**Pull request by nicholasrice**
# Description
The `FormAssociated` proxy element is appended to the host element when `ElementInternals` is not supported. This was causing checks for an empty default slot to have inconsistent behavior that depended on `ElementInternals` support.

This changes the way that the proxy is appended, creating a dedicated slot element for the proxy element and appending the slot element imperatively. This means the proxy will not be in the default slot and won't interfere with component implementations.

closes #3741

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

File: packages/web-components/fast-foundation/src/form-associated/form-associated.ts [hunk 1]
```diff
@@ -424,6 +430,8 @@ export abstract class FormAssociated<
      * Attach the proxy element to the DOM
      */
     protected attachProxy() {
+        const proxySlotName = "form-associated-proxy";
```
Comment (EisenbergEffect) [inline packages/web-components/fast-foundation/src/form-associated/form-associated.ts:433]: This can probably be lifted to the module scope.

File: packages/web-components/fast-foundation/src/form-associated/form-associated.ts [hunk 2]
```diff
@@ -444,8 +452,14 @@ export abstract class FormAssociated<
             if (typeof this.value === "string") {
                 this.proxy.value = this.value;
             }
+
+            this.proxy.setAttribute("slot", proxySlotName);
         }
 
+        this.proxySlot = document.createElement("slot");
+        this.proxySlot.setAttribute("name", proxySlotName);
```
Comment (EisenbergEffect) [inline packages/web-components/fast-foundation/src/form-associated/form-associated.ts:460]: Should these two lines be inside the `if` block as well? I was looking at the detachProxy code below and wondering if there was a need to re-create the slot or not.
