### PR TITLE
Fix toolbar stealing focus

### LINKED ISSUE #6842: Issue with focus on a toolbar clicked button
In the toolbar, when a item is clicked, the event (if propagated) will be used to change the active index (expected behavior). Then if the active index changes, the clicked item is focused through:

https://github.com/microsoft/fast/blob/6091f89a6a0b8bf3baa4cd4ed2aae1078ba9865b/packages/web-components/fast-foundation/src/toolbar/toolbar.ts#L247

That latter behavior can have inconsistent and unexpected result in the following case:
- When a button in the toolbar has a _mousedown_ listener changing the focus to a text area (outside the toolbar).
- If clicking on the button
- The focus is at the end on to the button (unexpected)

- On a second click on the button, the focus is in the text area (expected) because the active index did not change on the toolbar (the snippet above has not been called).

> If clicking on another item in the toolbar then back to the button, the case of first click occurs as the active index changes.

So I was wondering if it makes sense to not focus the active element either at all or at lease if the `preventDefault` was called on the click event.

Of note, most browsers are [focusing a button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus) on click. But this can be escaped by calling `preventDefault` on _mousedown_ event.

Screencast of the issue

toolbar_item_focus

### PR DESCRIPTION
**Pull request by fcollonval**
# Pull Request

## 📖 Description

If a toolbar element (e.g. a button) action results in changing the focus to an element somewhere in the page, the active toolbar element should not be focused by the toolbar.

This can be achieved by calling `preventDefault()` on the event.

### 🎫 Issues

Fixes #6842 

## 📑 Test Plan

I added a test with a toolbar button that set the focus to an external element. The test is against click and mouse down events.

### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

File: packages/web-components/fast-foundation/src/toolbar/toolbar.ts [hunk 1]
```diff
@@ -241,12 +242,15 @@ export class FASTToolbar extends FASTElement {
...
      * @param activeIndex - The new index to set
+     * @param enforceFocus - Whether to enforce the focus on the active element or not
      * @internal
      */
-    private setFocusedElement(activeIndex: number = this.activeIndex): void {
+    private setFocusedElement(activeIndex: number = this.activeIndex, enforceFocus: boolean = true): void {
         this.activeIndex = activeIndex;
         this.setFocusableElements();
-        this.focusableElements[this.activeIndex]?.focus();
+        if (enforceFocus) {
```
Comment (scomea) [inline packages/web-components/fast-foundation/src/toolbar/toolbar.ts:251]: What if instead of passing an "enforceFocus" param we instead did a check like
' if (this.contains(document.activeElement))'
which should only move focus if focus is currently in the toolbar?

Comment (scomea) [reply packages/web-components/fast-foundation/src/toolbar/toolbar.ts:251]: We do something similar in combobox -https://github.com/microsoft/fast/blob/9af1b251df57244d61524bf5af757839373249a0/packages/web-components/fast-foundation/src/combobox/combobox.ts#L339

Comment (scomea) [reply packages/web-components/fast-foundation/src/toolbar/toolbar.ts:251]: Good catch, btw.

Comment (fcollonval) [reply packages/web-components/fast-foundation/src/toolbar/toolbar.ts:251]: Thanks a lot for the review @scomea - your solution is much nicer.

Comment (scomea) [reply packages/web-components/fast-foundation/src/toolbar/toolbar.ts]: No worries, I did miss something though.  Can't simply check document.activeElement as that won't work right for toolbars in shadow dom so we should account for that.

Just copy this from data-grid-cell and get the active element from the function instead:

https://github.com/microsoft/fast/blob/961ebd203e9d2584940ca4849a65aa3ff3f781a1/packages/web-components/fast-foundation/src/data-grid/data-grid-cell.ts#L295C13-L295C33

We should probably consolidate that function into utilities and update combobox too (but not in this pr).

Comment (scomea) [reply packages/web-components/fast-foundation/src/toolbar/toolbar.ts]: https://github.com/microsoft/fast/pull/6899

**Comment by fcollonval** [comment]
Thanks @scomea for #6899 - I'll wait for it to update this PR with the utility method you introduced.

**Comment by fcollonval** [comment]
@scomea Would you mind having another look at this one?

**Review by bheston — APPROVED** [review]

File: change/@microsoft-fast-foundation-65238abc-a169-4169-a830-9dcdb4e9af99.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "patch",
```
Comment (scomea) [inline change/@microsoft-fast-foundation-65238abc-a169-4169-a830-9dcdb4e9af99.json:2]: prerelease

File: change/@microsoft-fast-foundation-65238abc-a169-4169-a830-9dcdb4e9af99.json [hunk 3]
```diff
@@ -0,0 +1,7 @@
...
+  "comment": "Fix toolbar stealing focus",
+  "packageName": "@microsoft/fast-foundation",
+  "email": "fcollonval@users.noreply.github.com",
+  "dependentChangeType": "patch"
```
Comment (scomea) [inline change/@microsoft-fast-foundation-65238abc-a169-4169-a830-9dcdb4e9af99.json:6]: prerelease

**Review by scomea — CHANGES_REQUESTED** [review]
Just the change comments, otherwise ok.  Correct those and we'll merge.

**Review by scomea — APPROVED** [review]
