### PR TITLE
Users/eisenbergeffect/repeat positioning update fix

### LINKED ISSUE #6379: fix: repeat directive indexing fails on splice of associated array
# 🐛 Bug Report
After a recent update my virtual list pr stopped working correctly.  The underlying issue turned out to be how the observed array used in the repeat directive was being manipulated which could result in the `c.index` value used in item bindings always reported the array length and not the item's index.  

When the list was updated with new items I had been using `splice` to clear out the old items and swap in the new items while maintaining the same array instance:

`this.visibleItems.splice(0, this.visibleItems.length, ...newVisibleItems);`

When I just swapped in a new array the `c.index` values are correct:

`this.visibleItems = newVisibleItems;`

## 🤔 Expected Behavior

Items generated by the repeat directive should get the correct value for `c.index` in template binding.

## 😯 Current Behavior

All items generated by the repeat directive get the list length as the value for `c.index` when the list has been manipulated by a `splice()`

## 🔦 Context

Repeat directives should pass correct index values to generated items regardless when associated array is modified.

### PR DESCRIPTION
**Pull request by EisenbergEffect**
# Pull Request

## 📖 Description

This PR fixes a major bug in `repeat` view updates when `positioning` is set to `true`.

### 🎫 Issues

* Fixes #6379 

## 👩‍💻 Reviewer Notes

This turned out to be a really simple fix. The `index` and `length` values on the `context` for a `repeat` view were swapped. 

## 📑 Test Plan

I added additional asserts to all `repeat` tests with `positioning: true` so that we can confirm the fix and prevent future regressions. All tests now pass with the new asserts.

### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

## ⏭ Next Steps

While tracking this down @scomea found a perf regression in repeat related to views that were unnecessarily being removed and re-added, causing internal element unbinds and rebinds. I plan to follow up with another PR to address this issue (once I figure out how to fix it that is). @prudepixie may also have some ideas about this.

### CODE REVIEW

File: packages/web-components/fast-element/src/templating/repeat.ts [hunk 1]
```diff
@@ -220,8 +223,8 @@ export class RepeatBehavior<TSource = any> implements ViewBehavior, Subscriber {
         if (this.directive.options.positioning) {
             for (let i = 0, ii = views.length; i < ii; ++i) {
                 const context = views[i].context;
-                context.length = i;
-                context.index = ii;
+                context.length = ii;
+                context.index = i;
```
Comment (EisenbergEffect) [inline packages/web-components/fast-element/src/templating/repeat.ts:227]: This is the actual fix. Everything else is test improvements to catch this.

**Review by scomea — APPROVED** [review]

**Review by janechu — APPROVED** [review]

**Review by chrisdholt — APPROVED** [review]

File: packages/web-components/fast-element/src/templating/repeat.ts (hunk 1 above)
Comment (radium-v) [reply packages/web-components/fast-element/src/templating/repeat.ts:227]: This sort of double assignment in a for loop is very unconventional. Is this approach used for performance reasons? Could it be rewritten to improve readability?

**Review by nicholasrice — APPROVED** [review]

File: packages/web-components/fast-element/src/templating/repeat.ts (hunk 1 above)
Comment (radium-v) [reply packages/web-components/fast-element/src/templating/repeat.ts:227]: would renaming `ii` to something like `viewsLength` make sense? That would go a long way for improving readability without affecting the routine.

**Review by radium-v — APPROVED** [review]

File: packages/web-components/fast-element/src/templating/repeat.ts (hunk 1 above)
Comment (EisenbergEffect) [reply packages/web-components/fast-element/src/templating/repeat.ts:227]: Yes. I was just thinking the same thing. Because the bug is so hard to see with the current variable names, which is probably why it happened in the first place. I'll make that improvement in just a sec.

Comment (EisenbergEffect) [reply packages/web-components/fast-element/src/templating/repeat.ts:227]: Pushed the change. Thanks @radium-v for the feedback!
