### PR TITLE
fix: accordion arrow key press moves focus from content to accordion header

### LINKED ISSUE #4326: accordion focus moves from focusable panel content to header when arrow key up or down are pressed
**Describe the bug; what happened?**
The focus is moving from accordion item panel focusable content back to the accordion headers when the down or up arrow keys are pressed.

**What are the steps to reproduce the issue?**

Example:

see stackblitz repro: https://stackblitz.com/edit/fast-design-tku4xg?file=index.html

1. Focus on accordion header
2. Tab focus to any button in panel
3. Press arrow up or down key
4. Notice how focus moves to accordion headers

**What behavior did you expect?**
The accordion item should _not_ handle arrow key presses or focus unless the focus is _already_ on the accordion headers.
See ARIA Spec Accordion Keyboard Interaction: https://w3c.github.io/aria-practices/#keyboard-interaction
> Down Arrow (Optional): If focus is on an accordion header, moves focus to the next accordion header. If focus is on the last accordion header, either does nothing or moves focus to the first accordion header.
Up Arrow (Optional): If focus is on an accordion header, moves focus to the previous accordion header. If focus is on the first accordion header, either does nothing or moves focus to the last accordion header.

**If applicable, provide screenshots:**
accordionkeycast

**In what environment did you see the issue?**

* OS & Device: MacOS, Windows, on PC
* Browser Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox

### PR DESCRIPTION
**Pull request by SethDonohue**
Added focusable content to default example
Added check for target to equal current target before handling accordion item key down event.

If the event.target and event.currentTarget are the same then the arrow key press happened on the accordion itself, which is the event we want to act on with arrow up/down keys.

Note: this _also_ makes focus _not_ move if it is on one of the start or end items in the accordion header. I believe this is the appropriate response, as that is focusable content so  the accordion item key down handler should not act on that. Only if the actual accordion item is focused do we want the arrow keys to move focus between accordion items.

# Description
 closes #4326 

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

File: packages/web-components/fast-foundation/src/accordion/accordion.ts [hunk 1]
```diff
@@ -125,25 +125,29 @@ export class Accordion extends FASTElement {
...
-                this.activeItemIndex = 0;
-                this.focusItem();
-                break;
-            case keyCodeEnd:
-                this.activeItemIndex = this.accordionItems.length - 1;
-                this.focusItem();
-                break;
+        // only handle the keydown if the event target is the accordion item
+        // prevents arrow keys from moving focus to accordion headers when focus is on accordion item panel content
+        if (event.target === event.currentTarget) {
```
Comment (radium-v) [inline packages/web-components/fast-foundation/src/accordion/accordion.ts:130]: nit: instead of wrapping the entire block, you could invert it and return when they're not equal.

**Review by radium-v — APPROVED** [review]

File: packages/web-components/fast-foundation/src/accordion/accordion.ts (hunk 1 above)
Comment (chrisdholt) [reply packages/web-components/fast-foundation/src/accordion/accordion.ts:130]: Yeah, would prefer a guard here rather than wrapping the entire block to execute. 

```
if (event.target !== event.currentTarget) {
    return;
}
```

**Review by EisenbergEffect — APPROVED** [review]

File: packages/web-components/fast-foundation/src/accordion/accordion.ts (hunk 1 above)
Comment (SethDonohue) [reply packages/web-components/fast-foundation/src/accordion/accordion.ts]: Updated!

**Review by chrisdholt — APPROVED** [review]
