### PR TITLE
fix: prevent events to propagate from disabled button (#4884)

### LINKED ISSUE #4884: fix: Click events on disabled fast-button bubble up the parent hierarchy
# 🐛 Bug Report

When a fast button is in disabled state click events on it are still propagated up the parent hierarchy.

This may be releated to #4698 and #4137, but since the observed behaviour does not affect the event listeners on the fast element, but the event propagation I am creating this separate issue.

The issue propably affects other input elements as well, but I only tested this on fast button for now.

## 💻 Repro or Code Sample

See [https://skaempfer.github.io/fast-button-click/](https://skaempfer.github.io/fast-button-click/) for a behaviour comparison between native button element and fast-button element 

## 🤔 Expected Behavior

Fast button element behaves like native button element: When in disabled state, fast-button elements do not propagate click events up their parent hierarchy. This should be in accordance with the HTML spec: "*A form control that is disabled must prevent any click events that are queued on the user interaction task source from being dispatched on the element.*" ([Source](https://www.w3.org/TR/html52/sec-forms.html#enabling-and-disabling-form-controls-the-disabled-attribute))

## 😯 Current Behavior

When you click on an disabled fast button any click listener on the element is not triggered, but the click event bubbles up the parent hierarchy.

## 💁 Possible Solution

The fast button element wraps a native button element. To behave like its native counterpart the fast button should make a descision on blocking or allowing event propagation based on the disabled state of the wrapped button element.

### PR DESCRIPTION
**Pull request by prudepixie**
# Pull Request

## 📖 Description
This change makes sure that the click events from fast-button in its disabled state behaves the same way as a native html button. 
Specifically, if text is not wrapped around addition html element, clicking on the button should not propagate events to the container div.
```
<div id="container">
   <fast-button disabled>Button</fast-button>
</div>
```

If in the following example, there is a span wrapped around text, then clicking on the span would propagate to the container as a span or any html element within a native button would behave.
```
<div id="container">
   <fast-button disabled><span>Button</span></fast-button>
</div>
```

### 🎫 Issues

fixes #4884 
### General

- [x] I have included a change request file using `$ yarn change`
- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## ⏭ Next Steps

There seems to be other components (fast-input?) that have similar issues where because of how the template is defined, the events behave differently as a native HTML element.

### CODE REVIEW

File: packages/web-components/fast-foundation/src/button/button.ts [hunk 1]
```diff
@@ -157,6 +157,25 @@ export class Button extends FormAssociatedButton {
 
         this.proxy.setAttribute("type", this.type);
         this.handleUnsupportedDelegatesFocus();
+        document.addEventListener('click', this.handleClick, true)
```
Comment (nicholasrice) [inline packages/web-components/fast-foundation/src/button/button.ts:160]: I don't think we need to watch the entire document to catch this - we could probably just listen on the internal `<button>` or `<span>` elements. That would provide ample opportunity to stop propagation without running this code for *every* click event that bubbles up to the document.

Comment (prudepixie) [reply packages/web-components/fast-foundation/src/button/button.ts]: Makes sense, something interesting to note here is that it doesn't seem possible to addEventLister to disabled buttons  , including the fast-button.
Might have something to do with the specs defined here (4.10.18.5): https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-fe-disabled 

So I'm going to add it to the #shadowRoot > button > span instead.

Comment (nicholasrice) [reply packages/web-components/fast-foundation/src/button/button.ts]: Yea that makes sense, thanks @prudepixie!

File: packages/web-components/fast-foundation/src/button/button.spec.ts [hunk 2]
```diff
@@ -563,4 +564,50 @@ describe("Button", () => {
             await disconnect();
         });
     });
+
+    describe("of 'disabled'", () => {
```
Comment (nicholasrice) [inline packages/web-components/fast-foundation/src/button/button.spec.ts:568]: Thanks for adding tests!

**Review by nicholasrice — APPROVED** [review]

File: packages/web-components/fast-foundation/src/button/button.ts [hunk 3]
```diff
@@ -157,8 +157,34 @@ export class Button extends FormAssociatedButton {
 
         this.proxy.setAttribute("type", this.type);
         this.handleUnsupportedDelegatesFocus();
+
+        const spans = this.shadowRoot?.querySelectorAll("span");
```
[the remark this answers is not in the document]
Comment (prudepixie) [reply packages/web-components/fast-foundation/src/button/button.ts:161]: Sounds good, I'll make that change

**Comment by chrisdholt** [comment]
Does this relate to #5433 ?

**Review by robarbms — APPROVED** [review]

File: packages/web-components/fast-foundation/src/button/button.ts [hunk 4]
```diff
@@ -157,8 +157,40 @@ export class Button extends FormAssociatedButton {
...
+            });
+        }
+    }
+
+    /**
+     * @internal
+     */
+    public disconnectedCallback(): void {
+        super.disconnectedCallback();
+        const elements = this.shadowRoot?.querySelectorAll("span");
```
Comment (nicholasrice) [inline packages/web-components/fast-foundation/src/button/button.ts:175]: We spoke offline but I wanted to make the note; We shouldn't access `this.shadowRoot` here because it will be `null` in cases of closed shadow roots and then this won't exhibit the desired behavior.

Comment (prudepixie) [reply packages/web-components/fast-foundation/src/button/button.ts]: I've made the update to add the click handler on the spans themselves @nicholasrice please take a look when you get a chance (particularly in the start-end.ts file), thanks!

File: packages/web-components/fast-foundation/src/patterns/start-end.ts [hunk 5]
```diff
@@ -63,6 +63,7 @@ export const endSlotTemplate: (
         part="end"
         ${ref("endContainer")}
         class=${x => (definition.end ? "end" : void 0)}
+        @click="${(x, c) => x.handleClick(c.event as Event)}"
```
Comment (nicholasrice) [inline packages/web-components/fast-foundation/src/patterns/start-end.ts:66]: I think we need to add the event handler imperativly via the `endContainer` ref. Adding the click handler to the template like this adds handle click behavior to *all* components that implement start / end and also assumes they have a method called 'handleClick', so this could easily throw at runtime.

Comment (prudepixie) [reply packages/web-components/fast-foundation/src/patterns/start-end.ts:66]: Got it! I'll make the change

Comment (prudepixie) [reply packages/web-components/fast-foundation/src/patterns/start-end.ts]: Ok I ended up adding the handler imperatively for all spans under the button control, let me know if it looks ok now @nicholasrice

File: packages/web-components/fast-foundation/src/button/button.ts (hunk 4 above)
Comment (nicholasrice) [reply packages/web-components/fast-foundation/src/button/button.ts]: Looks good, thanks!
