### PR TITLE
fix: fast anchor should not assign in constructor

### LINKED ISSUE #5687: fix: [what is the issue?] in [where is the issue?]
PR #5355 modified `fast-anchor` so that the appearance attribute is assigned in the constructor instead of in `connectedCallback()`:

https://github.com/microsoft/fast/blob/8da160bf10fc106917053350491fb88162d8bc45/packages/web-components/fast-components/src/anchor/index.ts#L28

Corresponding compiled JS code, extracted from `@microsoft\fast-components\dist\esm\anchor\index.js`:

```.javascript
    constructor() {
        super(...arguments);
        /**
         * The appearance the anchor should have.
         *
         * @public
         * @remarks
         * HTML Attribute: appearance
         */
        this.appearance = "neutral";
    }
```

This violates the "Requirements for custom element constructors and reactions" defined at https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance which says that "When authoring [custom element constructors](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-constructor), authors are bound by the following conformance requirements...The element must not gain any attributes or children, as this violates the expectations of consumers who use the [createElement](https://dom.spec.whatwg.org/#dom-document-createelement) or [createElementNS](https://dom.spec.whatwg.org/#dom-document-createelementns) methods."

In Microsoft Edge, attempting to create the element through `document.createElement` results in `Error: DOMException: Failed to construct 'CustomElement': The result must not have attributes`.

### PR DESCRIPTION
**Pull request by chrisdholt**
# Pull Request

## 📖 Description
This PR moves the assignment of appearance for anchor to `connectedCallback`.

### 🎫 Issues
closes #5687 

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by scomea — APPROVED** [review]

File: packages/web-components/fast-components/src/anchor/index.ts [hunk 1]
```diff
@@ -36,6 +36,14 @@ export class Anchor extends FoundationAnchor {
         }
```
Comment (nicholasrice) [inline packages/web-components/fast-components/src/anchor/index.ts:36]: I know this code isn't part of your change, but can we deprecate this class addition / removal behavior? It seems styling could just use the attribute, making the class un-necessary.

**Review by nicholasrice — APPROVED** [review]
