### PR TITLE
fix: removed disabled style on anchor web component

### LINKED ISSUE #4595: fix: remove disabled stylings in anchor component
# 🐛 Bug Report

I noticed that adding the `disabled` attribute to the anchor component styles it, where it has no disabled logic whatsoever.

You can track the discussion in [discord](https://discord.com/channels/449251231706251264/449251231706251266/832239386195394560)

## 💻 Repro or Code Sample

You can try it [here](https://explore.fast.design/components/fast-anchor)

## 🤔 Expected Behavior

Nothing :)

## 😯 Current Behavior

Anchor has a disabled UI, whereas it has no logic for disabled

## 💁 Possible Solution

Remove the disabled styles inherited from the button component

## 🌍 Your Environment

* OS & Device: OSX
* Browser Chrome
* Version Latest

### PR DESCRIPTION
**Pull request by khamudom**
# Pull Request

## 📖 Description

The anchor component should not have a `disabled` style, so I moved all the disabled selectors out of the common button styles file and added them to the ` button.styles` file. 

### 🎫 Issues

closes #4595 

### General

- [x] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Review by scomea — APPROVED** [review]

File: packages/web-components/fast-components/src/styles/patterns/button.ts [hunk 1]
```diff
@@ -187,21 +171,17 @@ export const AccentButtonStyles = css`
         color: ${accentForegroundCutRestBehavior.var};
     }
 
-    :host([appearance="accent"]:hover) {
+    :host([appearance="accent"]:hover:not([disabled])) {
```
Comment (chrisdholt) [inline packages/web-components/fast-components/src/styles/patterns/button.ts:174]: I'm slightly concerned at the complexity and specificity of the selectors here. My assumption is that this is due to the fact that we're adding these styles to the base button. What if we shared the styles we're applying to the base button across each of these appearances? Would this complex selector still be needed?

Comment (khamudom) [reply packages/web-components/fast-components/src/styles/patterns/button.ts]: I removed the :not pseudo class. what I decided to do was add hover and active on the disabled selectors for each appearance

**Review by chrisdholt — APPROVED** [review]

**Comment by nicholasrice** [comment]
Anchor doesn't support the `disabled` content attribute but it is valid to not have an `href` content attribute. I *sort of* consider that the anchor's equivalent of disabled. Is that a case we want to represent with anchor?

**Comment by khamudom** [comment]
> Anchor doesn't support the `disabled` content attribute but it is valid to not have an `href` content attribute. I _sort of_ consider that the anchor's equivalent of disabled. Is that a case we want to represent with anchor?

Not sure if this will answer your question, but this work is to just remove the disabled look to anchor.

**Comment by chrisdholt** [comment]
> Anchor doesn't support the `disabled` content attribute but it is valid to not have an `href` content attribute. I _sort of_ consider that the anchor's equivalent of disabled. Is that a case we want to represent with anchor?

@nicholasrice In this case would we still want to attach styles since this is technically just "text" in that case? I think we're headed towards a rabbit hole where guidance will be our best friend, but I think this is a worth while conversation. I'm curious what others think as well here - would what expected behavior be in this scenario? Styles or no styles? Disabled styles for non-hypertext?

File: packages/web-components/fast-components/src/styles/patterns/button.ts [hunk 2]
```diff
@@ -187,7 +171,7 @@ export const AccentButtonStyles = css`
         color: ${accentForegroundCutRestBehavior.var};
     }
 
-    :host([appearance="accent"]:hover) {
+    :host([appearance="accent"]:hover:) {
```
Comment (robarbms) [inline packages/web-components/fast-components/src/styles/patterns/button.ts:174]: Typo?

File: packages/web-components/fast-components/src/button/button.styles.ts [hunk 3]
```diff
@@ -1,18 +1,148 @@
...
+                        color: ${SystemColors.GrayText};
+                    }
+                `
+            )
+        )
+    ),
+    appearanceBehavior(
+        "lightweight",
+        css`
+            :host([appearance="lightweight"][disabled]),
```
Comment (robarbms) [inline packages/web-components/fast-components/src/button/button.styles.ts:70]: This doesn't appear to be needed since it's already declared by the default styles for :host([appearance="lightweight"]) on lines 301-304 in patterns/button.ts

File: packages/web-components/fast-components/src/button/button.styles.ts [hunk 4]
```diff
@@ -1,18 +1,148 @@
...
+            :host([appearance="lightweight"][disabled]:hover),
+            :host([appearance="lightweight"][disabled]:active) {
+                background-color: transparent;
```
Comment (robarbms) [inline packages/web-components/fast-components/src/button/button.styles.ts:73]: background-color: transparent doesn't look like its needed as well. It should be the default for all of these states as they are not changed for :hover or :active pseudo states in patterns/button.ts.

File: packages/web-components/fast-components/src/styles/patterns/button.ts (hunk 2 above)
Comment (khamudom) [reply packages/web-components/fast-components/src/styles/patterns/button.ts:174]: thanks. a PR will up shortly to fix this

File: packages/web-components/fast-components/src/button/button.styles.ts (hunk 4 above)
Comment (khamudom) [reply packages/web-components/fast-components/src/button/button.styles.ts:73]: this is still needed to overwrite the hover and active state on base button

File: packages/web-components/fast-components/src/button/button.styles.ts (hunk 3 above)
Comment (khamudom) [reply packages/web-components/fast-components/src/button/button.styles.ts:70]: yes, this is not needed
