### PR TITLE
fix: tree-view right and left arrow keyboarding should behave as wai-aria spec suggests

### LINKED ISSUE #3886: bug: nested tree views has odd arrow key behavior
**Describe the bug; what happened?**
Using arrow keys to navigate nested tree view has odd behaviors.
- sometimes pressing an arrow key does nothing, then pressing it again moves focus
- if you navigate to an item by pressing the right arrow key you should be able to go back by pressing left arrow key

**What are the steps to reproduce the issue?**

Go to https://explore.fast.design/components/fast-tree-view
click on tree item 1 to focus on it
press right arrow key, item opens
press right arrow key, focus to nested child
press rigth arrow key, nothing happens (?)
press right arrow key, focus to tree item 2
press left arrow key, nothing happens

**What behavior did you expect?**
Consistent and predictable arrow key navigation

### PR DESCRIPTION
**Pull request by marjonlynch**
# Description
* fixed a bug where hitting right arrow key on leaf node would mess up the next left arrow keydown
* right arrow key expands a node if not expanded, or moves to first child, or does nothing

closes #3886 

## Motivation & context
Expected keyboarding behavior for arrow keys and an example in action
https://w3c.github.io/aria-practices/#TreeView
https://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2a.html

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

- [ ] I have added a new component
- [x] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

File: packages/web-components/fast-foundation/src/tree-item/tree-item.ts [hunk 1]
```diff
@@ -235,10 +247,12 @@ export class TreeItem extends FASTElement {
             return;
         }
 
-        if (!this.expanded) {
+        if (!this.expanded && this.childItemLength() > 0) {
             this.setExpanded(true);
         } else {
-            this.focusNextNode(1);
+            if (this.childItemLength() > 0) {
+                this.enabledChildTreeItems()[0].focus();
```
Comment (EisenbergEffect) [inline packages/web-components/fast-foundation/src/tree-item/tree-item.ts:254]: Is it possible that childItemLengty is greater than 0 but that the enabled child tree items is 0?

Comment (chrisdholt) [reply packages/web-components/fast-foundation/src/tree-item/tree-item.ts:254]: I think this is technically possible and a good case to guard against. I think there was an email where I called this out as a noop ;). We should likely account for this. Good catch @eisenbergeffect!

Comment (marjonlynch) [reply packages/web-components/fast-foundation/src/tree-item/tree-item.ts:254]: doh! will fix

**Review by nicholasrice — APPROVED** [review]

**Review by janechu — APPROVED** [review]
