### PR TITLE
fix: add in missing attributes to the design system provider definition

### LINKED ISSUE #3974: fast-design-system-provider should allow users to set attributes in fast-component-explorer
**Describe the bug; what happened?**
* run fast-component-explorer
* insert a fast-design-system-provider in a default slot somewhere
* observe the only thing you can set is the default slot for the fast-design-system-provider
Screen Shot 2020-09-25 at 11 05 45 AM

**What behavior did you expect?**

I expect to be able to tweak the design system values, like luminance, density, etc...

**In what environment did you see the issue?**

Mac OS, Edge (production)

### PR DESCRIPTION
**Pull request by janechu**
# Description

This adds all attributes for the `<fast-design-system-provider>` into the definition file which will allow the tooling to show the full list of attributes to modify as form UI.

## Motivation & context

Resolves #3974

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

**Adding or modifying component(s) in `@microsoft/fast-components` checklist**

- [ ] I have added a new component
- [ ] I have modified an existing component
- [x] I have updated the [definition file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/Microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]

**Review by nicholasrice — APPROVED** [review]

**Review by awentzel — APPROVED** [review]

File: packages/web-components/fast-components/src/design-system-provider/design-system-provider.definition.ts [hunk 1]
```diff
@@ -1,12 +1,521 @@
...
+                    description: "Use default values",
+                    type: DataType.boolean,
+                    default: true,
+                    required: false,
+                },
+                {
+                    name: "no-paint",
+                    description: "Do not paint background",
+                    type: DataType.boolean,
+                    default: undefined,
```
Comment (robarbms) [inline packages/web-components/fast-components/src/design-system-provider/design-system-provider.definition.ts:24]: This is the only attribute missing a default. Should this default to true like use-defaults?

**Review by robarbms — APPROVED** [review]

File: packages/web-components/fast-components/src/design-system-provider/design-system-provider.definition.ts (hunk 1 above)
Comment (janechu) [reply packages/web-components/fast-components/src/design-system-provider/design-system-provider.definition.ts:24]: Whoops, you're right, although it should be false. Good catch.

```suggestion
                    default: false,
```
