### PR TITLE
fix: accordion "single" expand-mode instances should support defined expanded children

### LINKED ISSUE #6584: fix: Accordion does not process `expanded` attribute when `expand-mode` is set to `single`
# 🐛 Bug Report

The title sums it up.

The following:
```html
<fast-accordion expand-mode="single">
    <fast-accordion-item>
        <span slot="heading">Panel one</span>
        Panel one content
    </fast-accordion-item>
    <fast-accordion-item>
        <span slot="heading">Panel two</span>
        Panel two content
    </fast-accordion-item>
    <fast-accordion-item expanded>
        <span slot="heading">Panel three</span>
        Panel three content
    </fast-accordion-item>
</fast-accordion>
```
will display an accordion with its first item open.

## 💻 Repro or Code Sample

https://codepen.io/olaf-k/pen/gOjMJxM

## 🤔 Expected Behavior

The element with an `expanded` attribute should be open, the first or last of them if there are more than one (design choice).
The first element should be open by default if no item has the attribute.

## 😯 Current Behavior

`setItems()`, which is called during the Accordion initialization (I'm assuming by `accordionItemsChanged`) iterates through children items to set a `change` event listener and, when in single mode, closes all items but the one at `activeItemIndex`, which is unfortunately set at its default value ('0').

## 💁 Possible Solution

I'd move the last part of `setItems()` (which sets `aria-disabled` in single mode) to the beginning and make `expandedItem` visible to the function, so that when we come to the event listener loop, we just compare `item !== expandedItem` instead of `this.activeItemIndex !== index`.

Also, as `expanded` is a boolean attribute, `findExpandedItem` should check its presence (getAttribute not null), not if its value is `"true"`.

There's probably an opportunity for a better refactor that avoids going twice through children (`forEach` + `findExpandedItem`) but I'm too lazy for now.

### PR DESCRIPTION
**Pull request by chrisdholt**
# Pull Request

## 📖 Description
This PR refactors the behavior associated for "single" expand-mode accordion instances. It also fixes an issue where disabled buttons of accordion items were focusable via tabbing.

### 🎫 Issues
closes #6584

### General

- [ ] I have included a change request file using `$ yarn change`
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/microsoft/fast/blob/master/CONTRIBUTING.md) documentation and followed the [standards](/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component
- [ ] I have updated the [definition file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#definition)
- [ ] I have updated the [configuration file](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/CONTRIBUTING.md#configuration)

### CODE REVIEW

**Comment by chrisdholt** [comment]
@olaf-k I think this refactor should address the specific issue referenced around expand-mode supporting children decorated with expanded. If there are multiple items decorated with `expanded`, I think we need to defer to the first instance considering we can't infer "intent" between the two. The exception to this would be disabled items which are expanded.

File: packages/web-components/fast-foundation/src/accordion/accordion.ts [hunk 1]
```diff
@@ -111,18 +110,28 @@ export class FASTAccordion extends FASTElement {
             item.addEventListener("keydown", this.handleItemKeyDown);
             item.addEventListener("focus", this.handleItemFocus);
         });
+
         if (this.isSingleExpandMode()) {
-            const expandedItem: FASTAccordionItem | null =
-                this.findExpandedItem() ??
-                ((this._accordionItems[0] as unknown) as FASTAccordionItem);
-            expandedItem.setAttribute("aria-disabled", "true");
+            const expandedItem = this.findExpandedItem() as FASTAccordionItem;
```
Comment (radium-v) [inline packages/web-components/fast-foundation/src/accordion/accordion.ts:115]: Does this type casting account for a situation where there are no accordion items?

File: packages/web-components/fast-foundation/src/accordion/accordion.ts [hunk 2]
```diff
@@ -67,13 +67,16 @@ export class FASTAccordion extends FASTElement {
...
-                return (this._accordionItems[item] as unknown) as FASTAccordionItem;
+            if (
+                ((this._accordionItems[item] as unknown) as FASTAccordionItem)
+                    .expanded === true
+            ) {
+                return this._accordionItems[item];
             }
         }
-        return null;
+        return this._accordionItems[0];
```
Comment (radium-v) [inline packages/web-components/fast-foundation/src/accordion/accordion.ts:79]: Will `this._accordionItems[0]` always exist in this situation?

File: packages/web-components/fast-foundation/src/accordion/accordion.ts [hunk 3]
```diff
@@ -67,13 +67,16 @@ export class FASTAccordion extends FASTElement {
...
     }
```
Comment (radium-v) [inline packages/web-components/fast-foundation/src/accordion/accordion.ts:80]: Is a for-loop needed here for performance? This function could be condensed:

```ts
private findExpandedItem(): FASTAccordionItem | Element {
    return (
        this._accordionItems.find((item: FASTAccordionItem) => item.expanded) ??
        this._accordionItems[0]
    );
}
```

File: packages/web-components/fast-foundation/src/accordion/accordion.ts [hunk 4]
```diff
@@ -111,18 +110,28 @@ export class FASTAccordion extends FASTElement {
...
-        this.accordionItems.forEach((item: FASTAccordionItem, index: number) => {
-            item.expanded = false;
+    private setSingleExpandMode(expandedItem: Element): void {
+        const currentItems = Array.from(this._accordionItems);
+        this.activeItemIndex = currentItems.indexOf(expandedItem);
+
+        currentItems.forEach((item: FASTAccordionItem, index: number) => {
+            if (this.activeItemIndex === index) {
+                item.expanded = true;
+                item.expandbutton.setAttribute("aria-disabled", "true");
```
Comment (radium-v) [inline packages/web-components/fast-foundation/src/accordion/accordion.ts:127]: Can this be handled with an observable on the `disabled` property in the `accordion-item`?

File: packages/web-components/fast-foundation/src/accordion/accordion.ts [hunk 5]
```diff
@@ -111,18 +110,28 @@ export class FASTAccordion extends FASTElement {
...
+            } else {
+                item.expanded = false;
+
+                if (!item.hasAttribute("disabled")) {
+                    item.removeAttribute("aria-disabled");
+                }
```
Comment (radium-v) [inline packages/web-components/fast-foundation/src/accordion/accordion.ts:133]: Same here, could this be handled with the observable `disabled` for the `accordion-item`?

File: packages/web-components/fast-foundation/src/accordion/accordion.ts (hunk 2 above)
Comment (chrisdholt) [reply packages/web-components/fast-foundation/src/accordion/accordion.ts:79]: I moved the deafult down but this is a good catch. I think the whole file probably needs to guard against it better.

File: packages/web-components/fast-foundation/src/accordion/accordion.ts (hunk 1 above)
Comment (chrisdholt) [reply packages/web-components/fast-foundation/src/accordion/accordion.ts:115]: It doesn't - I think a pass can probably be done to guard against all this.

File: packages/web-components/fast-foundation/src/accordion/accordion.ts (hunk 3 above)
Comment (chrisdholt) [reply packages/web-components/fast-foundation/src/accordion/accordion.ts:80]: I kept it relative to not making too many changes, but it's a good improvement.

File: packages/web-components/fast-foundation/src/accordion/accordion.ts (hunk 4 above)
Comment (chrisdholt) [reply packages/web-components/fast-foundation/src/accordion/accordion.ts:127]: I don't think so for this scenario as it's somewhat unique. This is specifically different than a _disabled_ item holistically and disabling the _button_ of the active item in single-expand mode.

File: packages/web-components/fast-foundation/src/accordion/accordion.ts (hunk 5 above)
Comment (chrisdholt) [reply packages/web-components/fast-foundation/src/accordion/accordion.ts:133]: I think the code here is slightly wrong, but as noted above this is different than disabling an item and more about disabling the button of the item to prevent the open item from collapsing in single-expand mode. More here: https://www.w3.org/WAI/ARIA/apg/patterns/accordion/

File: packages/web-components/fast-foundation/src/accordion/accordion.ts (hunk 2 above)
Comment (chrisdholt) [reply packages/web-components/fast-foundation/src/accordion/accordion.ts:79]: I've added a couple guards to ensure we don't operate and will push up the changes.

**Comment by olaf-k** [comment]
> @olaf-k I think this refactor should address the specific issue referenced around expand-mode supporting children decorated with expanded. If there are multiple items decorated with `expanded`, I think we need to defer to the first instance considering we can't infer "intent" between the two. The exception to this would be disabled items which are expanded.

Sounds good! Thank you for the update Chris.

**Review by nicholasrice — APPROVED** [review]

**Review by radium-v — APPROVED** [review]

**Comment by yinonov** [comment]
as this is a fix, shouldn't this merge to stable?
